/*Create warehouse*/
CREATE WAREHOUSE AI_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

/*Create database*/
CREATE DATABASE AI_GOVERNANCE_DB;

USE ROLE SECURITYADMIN;

/*Create roles*/

CREATE ROLE AI_CHATBOT_ROLE;
CREATE ROLE AI_ADMIN_ROLE;
CREATE ROLE AI_DEVELOPER_ROLE;
CREATE ROLE AI_READONLY_ROLE;

GRANT USAGE ON DATABASE AI_GOVERNANCE_DB TO ROLE AI_CHATBOT_ROLE;
GRANT USAGE ON WAREHOUSE AI_WH TO ROLE AI_CHATBOT_ROLE;

GRANT ROLE AI_CHATBOT_ROLE
TO ROLE AI_DEVELOPER_ROLE;

GRANT ROLE AI_READONLY_ROLE
TO ROLE AI_DEVELOPER_ROLE;

GRANT ROLE AI_DEVELOPER_ROLE
TO ROLE AI_ADMIN_ROLE;

/*Grant role access to the user*/

SELECT CURRENT_USER();

GRANT ROLE AI_CHATBOT_ROLE TO USER userid;
GRANT ROLE AI_ADMIN_ROLE TO USER userid;
SHOW GRANTS TO USER userid;

/*create metadata schema and tables*/

USE ROLE SYSADMIN;

USE DATABASE AI_GOVERNANCE_DB;

CREATE SCHEMA IF NOT EXISTS GOVERNANCE_METADATA;

USE SCHEMA GOVERNANCE_METADATA;

CREATE OR REPLACE TABLE DATA_ASSET
(
    ASSET_ID            NUMBER AUTOINCREMENT,
    DATABASE_NAME       VARCHAR(255) NOT NULL,
    SCHEMA_NAME         VARCHAR(255) NOT NULL,
    OBJECT_NAME         VARCHAR(255) NOT NULL,
    COLUMN_NAME         VARCHAR(255),
    ASSET_TYPE          VARCHAR(50) NOT NULL,
    DATA_TYPE           VARCHAR(100),
    BUSINESS_NAME       VARCHAR(255),
    DESCRIPTION         VARCHAR(1000),
    DATA_OWNER          VARCHAR(255),
    DATA_STEWARD        VARCHAR(255),
    DOMAIN_NAME         VARCHAR(100),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DATA_ASSET PRIMARY KEY (ASSET_ID)
);

CREATE OR REPLACE TABLE DATA_CLASSIFICATION
(
    CLASSIFICATION_ID       NUMBER AUTOINCREMENT,
    ASSET_ID                NUMBER NOT NULL,
    CLASSIFICATION_TYPE     VARCHAR(100) NOT NULL,
    CLASSIFICATION_VALUE    VARCHAR(100) NOT NULL,
    SENSITIVITY_LEVEL       VARCHAR(50),
    REGULATORY_FRAMEWORK    VARCHAR(100),
    CLASSIFICATION_SOURCE   VARCHAR(50),
    CLASSIFIED_BY           VARCHAR(255),
    CLASSIFIED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEW_STATUS           VARCHAR(50) DEFAULT 'APPROVED',
    NOTES                   VARCHAR(1000),

    CONSTRAINT PK_DATA_CLASSIFICATION
        PRIMARY KEY (CLASSIFICATION_ID),

    CONSTRAINT FK_CLASSIFICATION_ASSET
        FOREIGN KEY (ASSET_ID)
        REFERENCES DATA_ASSET (ASSET_ID)
);

CREATE OR REPLACE TABLE MASKING_POLICY_MAPPING
(
    MAPPING_ID          NUMBER AUTOINCREMENT,
    ASSET_ID            NUMBER NOT NULL,
    POLICY_DATABASE     VARCHAR(255),
    POLICY_SCHEMA       VARCHAR(255),
    POLICY_NAME         VARCHAR(255) NOT NULL,
    MASKING_STRATEGY    VARCHAR(100),
    APPLIES_TO_ROLE     VARCHAR(255),
    EXEMPT_ROLE         VARCHAR(255),
    POLICY_STATUS       VARCHAR(50) DEFAULT 'ACTIVE',
    APPLIED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_VERIFIED_AT    TIMESTAMP_NTZ,
    NOTES               VARCHAR(1000),

    CONSTRAINT PK_MASKING_POLICY_MAPPING
        PRIMARY KEY (MAPPING_ID),

    CONSTRAINT FK_MASKING_ASSET
        FOREIGN KEY (ASSET_ID)
        REFERENCES DATA_ASSET (ASSET_ID)
);

CREATE OR REPLACE TABLE ROLE_HIERARCHY
(
    ROLE_HIERARCHY_ID   NUMBER AUTOINCREMENT,
    PARENT_ROLE_NAME    VARCHAR(255) NOT NULL,
    CHILD_ROLE_NAME     VARCHAR(255) NOT NULL,
    HIERARCHY_STATUS    VARCHAR(50) DEFAULT 'ACTIVE',
    GRANTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    GRANTED_BY          VARCHAR(255),
    NOTES               VARCHAR(1000),

    CONSTRAINT PK_ROLE_HIERARCHY
        PRIMARY KEY (ROLE_HIERARCHY_ID)
);

CREATE OR REPLACE TABLE OBJECT_GRANT
(
    OBJECT_GRANT_ID     NUMBER AUTOINCREMENT,
    ROLE_NAME           VARCHAR(255) NOT NULL,
    PRIVILEGE_NAME      VARCHAR(100) NOT NULL,
    OBJECT_TYPE         VARCHAR(100) NOT NULL,
    DATABASE_NAME       VARCHAR(255),
    SCHEMA_NAME         VARCHAR(255),
    OBJECT_NAME         VARCHAR(255),
    COLUMN_NAME         VARCHAR(255),
    ASSET_ID            NUMBER,
    GRANT_OPTION        BOOLEAN DEFAULT FALSE,
    GRANT_STATUS        VARCHAR(50) DEFAULT 'ACTIVE',
    GRANTED_BY          VARCHAR(255),
    GRANTED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_OBJECT_GRANT
        PRIMARY KEY (OBJECT_GRANT_ID),

    CONSTRAINT FK_OBJECT_GRANT_ASSET
        FOREIGN KEY (ASSET_ID)
        REFERENCES DATA_ASSET (ASSET_ID)
);

/*Insert sample data to metadata tables*/
INSERT INTO DATA_ASSET
(
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    COLUMN_NAME,
    ASSET_TYPE,
    DATA_TYPE,
    BUSINESS_NAME,
    DESCRIPTION,
    DATA_OWNER,
    DATA_STEWARD,
    DOMAIN_NAME
)
VALUES
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    NULL,
    'TABLE',
    NULL,
    'Employee',
    'Master employee information',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'EMP_ID',
    'COLUMN',
    'NUMBER',
    'Employee Identifier',
    'Unique identifier for an employee',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'EMP_NAME',
    'COLUMN',
    'VARCHAR',
    'Employee Name',
    'Full name of the employee',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'EMAIL',
    'COLUMN',
    'VARCHAR',
    'Employee Email',
    'Corporate email address',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'NATIONAL_INSURANCE_NUMBER',
    'COLUMN',
    'VARCHAR',
    'National Insurance Number',
    'UK National Insurance identifier',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'SALARY',
    'COLUMN',
    'NUMBER',
    'Annual Salary',
    'Employee annual gross salary',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
),
(
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'EMPLOYEE',
    'DEPARTMENT',
    'COLUMN',
    'VARCHAR',
    'Department',
    'Employee organisational department',
    'HR_DIRECTOR',
    'HR_DATA_STEWARD',
    'HUMAN_RESOURCES'
);


INSERT INTO DATA_CLASSIFICATION
(
    ASSET_ID,
    CLASSIFICATION_TYPE,
    CLASSIFICATION_VALUE,
    SENSITIVITY_LEVEL,
    REGULATORY_FRAMEWORK,
    CLASSIFICATION_SOURCE,
    CLASSIFIED_BY,
    NOTES
)
SELECT
    ASSET_ID,
    'DATA_CATEGORY',
    'PII',
    'CONFIDENTIAL',
    'UK_GDPR',
    'MANUAL',
    'HR_DATA_STEWARD',
    'Employee name is personal data'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'EMP_NAME';

  INSERT INTO DATA_CLASSIFICATION
(
    ASSET_ID,
    CLASSIFICATION_TYPE,
    CLASSIFICATION_VALUE,
    SENSITIVITY_LEVEL,
    REGULATORY_FRAMEWORK,
    CLASSIFICATION_SOURCE,
    CLASSIFIED_BY,
    NOTES
)
SELECT
    ASSET_ID,
    'DATA_CATEGORY',
    'PII',
    'CONFIDENTIAL',
    'UK_GDPR',
    'MANUAL',
    'HR_DATA_STEWARD',
    'Email address is personal data'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'EMAIL';

  INSERT INTO DATA_CLASSIFICATION
(
    ASSET_ID,
    CLASSIFICATION_TYPE,
    CLASSIFICATION_VALUE,
    SENSITIVITY_LEVEL,
    REGULATORY_FRAMEWORK,
    CLASSIFICATION_SOURCE,
    CLASSIFIED_BY,
    NOTES
)
SELECT
    ASSET_ID,
    'PII_TYPE',
    'NATIONAL_IDENTIFIER',
    'RESTRICTED',
    'UK_GDPR',
    'MANUAL',
    'HR_DATA_STEWARD',
    'Highly sensitive national identifier'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'NATIONAL_INSURANCE_NUMBER';

  INSERT INTO DATA_CLASSIFICATION
(
    ASSET_ID,
    CLASSIFICATION_TYPE,
    CLASSIFICATION_VALUE,
    SENSITIVITY_LEVEL,
    REGULATORY_FRAMEWORK,
    CLASSIFICATION_SOURCE,
    CLASSIFIED_BY,
    NOTES
)
SELECT
    ASSET_ID,
    'DATA_CATEGORY',
    'FINANCIAL',
    'RESTRICTED',
    'INTERNAL_POLICY',
    'MANUAL',
    'HR_DATA_STEWARD',
    'Employee compensation information'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'SALARY';

  INSERT INTO MASKING_POLICY_MAPPING
(
    ASSET_ID,
    POLICY_DATABASE,
    POLICY_SCHEMA,
    POLICY_NAME,
    MASKING_STRATEGY,
    APPLIES_TO_ROLE,
    EXEMPT_ROLE,
    POLICY_STATUS,
    NOTES
)
SELECT
    ASSET_ID,
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'MASK_NATIONAL_INSURANCE_NUMBER',
    'PARTIAL_MASK',
    'AI_CHATBOT_ROLE',
    'AI_ADMIN_ROLE',
    'ACTIVE',
    'Shows only the final four characters to restricted users'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'NATIONAL_INSURANCE_NUMBER';

  INSERT INTO MASKING_POLICY_MAPPING
(
    ASSET_ID,
    POLICY_DATABASE,
    POLICY_SCHEMA,
    POLICY_NAME,
    MASKING_STRATEGY,
    APPLIES_TO_ROLE,
    EXEMPT_ROLE,
    POLICY_STATUS,
    NOTES
)
SELECT
    ASSET_ID,
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'MASK_EMPLOYEE_SALARY',
    'FULL_MASK',
    'AI_CHATBOT_ROLE',
    'AI_ADMIN_ROLE',
    'ACTIVE',
    'Salary is hidden from non-authorised roles'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND COLUMN_NAME = 'SALARY';

  INSERT INTO ROLE_HIERARCHY
(
    PARENT_ROLE_NAME,
    CHILD_ROLE_NAME,
    GRANTED_BY,
    NOTES
)
VALUES
(
    'AI_ADMIN_ROLE',
    'AI_DEVELOPER_ROLE',
    'SECURITYADMIN',
    'Application administrator inherits developer privileges'
),
(
    'AI_DEVELOPER_ROLE',
    'AI_CHATBOT_ROLE',
    'SECURITYADMIN',
    'Developer inherits chatbot read privileges'
);

INSERT INTO OBJECT_GRANT
(
    ROLE_NAME,
    PRIVILEGE_NAME,
    OBJECT_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    ASSET_ID,
    GRANT_OPTION,
    GRANTED_BY
)
SELECT
    'AI_CHATBOT_ROLE',
    'SELECT',
    'TABLE',
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    ASSET_ID,
    FALSE,
    'SECURITYADMIN'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND ASSET_TYPE = 'TABLE';

  INSERT INTO OBJECT_GRANT
(
    ROLE_NAME,
    PRIVILEGE_NAME,
    OBJECT_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    ASSET_ID,
    GRANT_OPTION,
    GRANTED_BY
)
SELECT
    'AI_DEVELOPER_ROLE',
    'SELECT',
    'TABLE',
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    ASSET_ID,
    FALSE,
    'SECURITYADMIN'
FROM DATA_ASSET
WHERE OBJECT_NAME = 'EMPLOYEE'
  AND ASSET_TYPE = 'TABLE';

  INSERT INTO OBJECT_GRANT
(
    ROLE_NAME,
    PRIVILEGE_NAME,
    OBJECT_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    OBJECT_NAME,
    GRANT_OPTION,
    GRANTED_BY
)
VALUES
(
    'AI_CHATBOT_ROLE',
    'USAGE',
    'DATABASE',
    'AI_GOVERNANCE_DB',
    NULL,
    'AI_GOVERNANCE_DB',
    FALSE,
    'SECURITYADMIN'
),
(
    'AI_CHATBOT_ROLE',
    'USAGE',
    'SCHEMA',
    'AI_GOVERNANCE_DB',
    'GOVERNANCE',
    'GOVERNANCE',
    FALSE,
    'SECURITYADMIN'
);


USE ROLE SECURITYADMIN;

GRANT USAGE
ON DATABASE AI_GOVERNANCE_DB
TO ROLE AI_CHATBOT_ROLE;

GRANT USAGE
ON SCHEMA AI_GOVERNANCE_DB.GOVERNANCE_METADATA
TO ROLE AI_CHATBOT_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA AI_GOVERNANCE_DB.GOVERNANCE_METADATA
TO ROLE AI_CHATBOT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA AI_GOVERNANCE_DB.GOVERNANCE_METADATA
TO ROLE AI_CHATBOT_ROLE;